# Compilation croisée Linux → Windows 64 bits avec llvm-mingw et Qt 6.8.2 (win64_llvm_mingw)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TC ${CMAKE_CURRENT_LIST_DIR}/llvm-mingw-20231128-ucrt-ubuntu-20.04-x86_64)
set(CMAKE_C_COMPILER ${TC}/bin/x86_64-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER ${TC}/bin/x86_64-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER ${TC}/bin/x86_64-w64-mingw32-windres)
set(QT_WIN ${CMAKE_CURRENT_LIST_DIR}/qt)
set(CMAKE_FIND_ROOT_PATH ${TC}/x86_64-w64-mingw32 ${QT_WIN})
set(CMAKE_PREFIX_PATH ${QT_WIN})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# outils Qt (moc…) de l'installation Linux, même version 6.8.2
set(QT_HOST_PATH /usr)
set(QT_HOST_PATH_CMAKE_DIR /usr/lib/x86_64-linux-gnu/cmake)
